version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    cooldown:
      default-days: 7
    target-branch: "main"
    labels:
      - "dependencies 🔁"
      - "ci/cd 👷‍♂️"
    assignees:
      - "pcaversaccio"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
